GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
Content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtjQmlzc2UiLCJpZCI6IjYwYzQ4ZjBjMmFlZDVlMGNmZDI0OTdiNiIsImlhdCI6MTYyMzU3MTg3N30.ugfmbZSt0CWwLEbEQDFh0va7pfaVl5svDiMvjNb8DVo
{
    "content": "Wanglung was a hard worker",
    "important": true

}

###
DELETE http://localhost:3001/api/notes/60b4e3bcf2520b19166b252d