GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "Live in the moment to enjoy the life",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "important": true,
    "userId": "60c48f0c2aed5e0cfd2497b6"
}

###
DELETE http://localhost:3001/api/notes/60b4e3bcf2520b19166b252d