GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "pe",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/60b4e3bcf2520b19166b252d